### ISSUE TITLE
Error when generating in DoorDevUnstable

### ISSUE THREAD

**Issue by zig-for** [aerinon/ALttPDoorRandomizer#71]
Traceback (most recent call last):
  File "D:\dev\New folder\ALttPDoorRandomizer\source\gui\bottom.py", line 107, in generateRom
    main(seed=guiargs.seed, args=guiargs, fish=parent.fish)
  File "D:\dev\New folder\ALttPDoorRandomizer\Main.py", line 222, in main
    patch_rom(world, rom, player, team, enemized)
  File "D:\dev\New folder\ALttPDoorRandomizer\Rom.py", line 1336, in patch_rom
    is_small_key_this_dungeon = hera_basement.dungeon.name == item_dungeon
AttributeError: 'Location' object has no attribute 'dungeon'

**Comment by aerinon** [comment]
Fixed I believe
