### ISSUE TITLE
Does not run if working directory is outside of project folder

### ISSUE THREAD

**Issue by vmrosetta** [aerinon/ALttPDoorRandomizer#75]
```
[rosetta@zenobia ~]$ python git/ALttPDoorRandomizer/Gui.py 
Traceback (most recent call last):
  File "/home/rosetta/git/ALttPDoorRandomizer/Gui.py", line 197, in <module>
    args = parse_cli(None)
  File "/home/rosetta/git/ALttPDoorRandomizer/CLI.py", line 41, in parse_cli
    with open(os.path.join("resources","app","cli","args.json")) as argsFile:
FileNotFoundError: [Errno 2] No such file or directory: 'resources/app/cli/args.json'
[rosetta@zenobia ~]$ cd git/ALttPDoorRandomizer/ ; python Gui.py
(runs)
```
Many files fetch needed files using a relative path to the project root directory.

**Comment by aerinon** [comment]
Yeah, I'm probably not fixing this anytime soon
